### ISSUE TITLE
Multi-server

### ISSUE THREAD

**Issue by Noitidart** [ghaiklor/sails-hook-cron#266]
This is awesome thanks for it! How does this work across multiple servers?

**Comment by ghaiklor** [comment]
It is just a hook for Sails framework. All the distributed logic you need to implement yourself :)
Sails gets a hook and runs it once per instance. So it will run your cron job per instance.

E.g. if you have a cluster where 20 instances of Sails is running it will run this hook 20 times.

**Comment by Noitidart** [comment]
Thanks for the fast reply I just saw it. THank you!

**Comment by gopalkohli** [comment]
If are using PM2, You can use an environment variable provided by PM2 itself called NODE_APP_INSTANCE which requires PM2 2.5 or greater.

NODE_APP_INSTANCE environment variable can be used to determine the difference between processes, for example, you may want to run a cronjob only on one process, you can just do this

if(process.env.NODE_APP_INSTANCE == 0) {
   //schedule your cron job here since this part will be executed for only one cluster
 } ,

Since two processes can never have the same number.
