### ISSUE TITLE
Is this hook cluster-safe?

### ISSUE THREAD

**Issue by Thelmos** [ghaiklor/sails-hook-cron#49]
I suppose jobs are executed in all nodes at the same time, or there is some class of syncronization (ie  using Redis) to avoid that?

**Comment by ghaiklor** [comment]
@Thelmos this module is not support synchronization. It's a simple implementation.

**Comment by Thelmos** [comment]
Ok, thanks, it's a nice way to plug cron in Sails anyway.

For anyone waiting for a solution, I'm trying to use pm2 api to only execute jobs only in first cluster instance, hope i can get it working.

**Comment by ghaiklor** [comment]
@Thelmos it can be achieved with separate single server also. But if you have some complex logic for background jobs then better to use queues like RabbitMQ.

**Comment by gopalkohli** [comment]
If are using PM2, You can use an environment variable provided by PM2 itself called NODE_APP_INSTANCE which requires PM2 2.5 or greater.

NODE_APP_INSTANCE environment variable can be used to determine the difference between processes, for example, you may want to run a cronjob only on one process, you can just do this

if(process.env.NODE_APP_INSTANCE == 0) {
   //schedule your cron job here since this part will be executed for only one cluster
 } ,

Since two processes can never have the same number.
